
USE STREAMING_DATABASE;
GO

--1. Visualizar todos os dados e colunas de cada uma das tabelas;
SELECT * FROM DBO.ASSINATURA;

SELECT * FROM DBO.CLIENTE;

SELECT * FROM DBO.CONTEUDO;

SELECT * FROM DBO.ENDERECO;

SELECT * FROM DBO.FUNCIONARIO;

SELECT * FROM DBO.PAGAMENTO;

SELECT * FROM DBO.RESIDENCIA;

SELECT * FROM DBO.SERVICO;

SELECT * FROM DBO.TELEFONE;

--2. Contar quantos registros tem em cada tabela;
SELECT COUNT(*) FROM DBO.ASSINATURA;

SELECT COUNT(*) FROM DBO.CLIENTE;

SELECT COUNT(*) FROM DBO.CONTEUDO;

SELECT COUNT(*) FROM DBO.ENDERECO;

SELECT COUNT(*) FROM DBO.FUNCIONARIO;

SELECT COUNT(*) FROM DBO.PAGAMENTO;

SELECT COUNT(*) FROM DBO.RESIDENCIA;

SELECT COUNT(*) FROM DBO.SERVICO;

SELECT COUNT(*) FROM DBO.TELEFONE;