
USE STREAMING_DATABASE;
GO


INSERT INTO DBO.CONTEUDO
VALUES('Star Wars I', 'filme', 'ficção, ação, guerra', 'Guerra nas estrelas', '1999');

INSERT INTO DBO.CONTEUDO
VALUES('Star Wars II', 'filme', 'ficção, ação, guerra', 'Guerra nas estrelas', '2002');

INSERT INTO DBO.CONTEUDO
VALUES('Star Wars III', 'filme', 'ficção, ação, guerra', 'Guerra nas estrelas', '2005');

INSERT INTO DBO.CONTEUDO
VALUES('Star Wars IV', 'filme', 'ficção, ação, guerra', 'Guerra nas estrelas', '1977');

INSERT INTO DBO.CONTEUDO
VALUES('Star Wars V', 'filme', 'ficção, ação, guerra', 'Guerra nas estrelas', '1980');

INSERT INTO DBO.CONTEUDO
VALUES('Star Wars VI', 'filme', 'ficção, ação, guerra', 'Guerra nas estrelas', '1983');

INSERT INTO DBO.CONTEUDO
VALUES('Back To The Future I', 'filme', 'ficção, ação, aventura', 'De Volta para o futuro', '1985');
INSERT INTO DBO.CONTEUDO
VALUES('Back To The Future II', 'filme', 'ficção, ação, aventura', 'De Volta para o futuro', '1989');
INSERT INTO DBO.CONTEUDO
VALUES('Back To The Future III', 'filme', 'ficção, ação, aventura', 'De Volta para o futuro', '1990');

INSERT INTO DBO.CONTEUDO
VALUES('CARS', 'filme', 'animação, familia', 'carros', '2006');
INSERT INTO DBO.CONTEUDO
VALUES('CARS II', 'filme', 'animação, familia', 'carros', '2011');
INSERT INTO DBO.CONTEUDO
VALUES('CARS III', 'filme', 'animação, familia', 'carros', '2017');

INSERT INTO DBO.CONTEUDO
VALUES('Pride e Prejudice', 'filme', 'romace, drama, literatura', 'Orgulho e preconceito', '2005');
INSERT INTO DBO.CONTEUDO
VALUES('My Big Fat Greek Weiding', 'filme', 'romance, comédia, familia', 'Casamento grego', '2002');

INSERT INTO DBO.CONTEUDO
VALUES('Friends', 'seriado', 'romance, comédia, familia', 'sitcom', '1994-2004');
INSERT INTO DBO.CONTEUDO
VALUES('The Good Place', 'seriado', 'romance, comédia, familia', 'sitcom', '2016-2020');
INSERT INTO DBO.CONTEUDO
VALUES('How I Met Your Mother', 'seriado', 'romance, comédia, familia', 'sitcom', '2005-2014');

--DELETE FROM DBO.CONTEUDO WHERE ID = 1;
--UPDATE CONTEUDO SET NOME = 'The wizard' WHERE ID = 18;

INSERT INTO DBO.RESIDENCIA
VALUES('CASA');
INSERT INTO DBO.RESIDENCIA
VALUES('APARTAMENTO');
INSERT INTO DBO.RESIDENCIA
VALUES('CASA');
INSERT INTO DBO.RESIDENCIA
VALUES('CASA');
INSERT INTO DBO.RESIDENCIA
VALUES('APARTAMENTO');
INSERT INTO DBO.RESIDENCIA
VALUES('CASA');
INSERT INTO DBO.RESIDENCIA
VALUES('CASA');
INSERT INTO DBO.RESIDENCIA
VALUES('APARTAMENTO');
INSERT INTO DBO.RESIDENCIA
VALUES('APARATAMENTO');
INSERT INTO DBO.RESIDENCIA
VALUES('APARTAMENTO');
INSERT INTO DBO.RESIDENCIA
VALUES('CASA');

--DELETE FROM DBO.RESIDENCIA WHERE ID = 1;

INSERT INTO DBO.ENDERECO
VALUES('Figuereido de Souza', 'Logradouro', 21, 58042-220, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('São Pedro', 'Igreja', 33, 47512-321, 'Nazaré', 'Fátima', 'Portugal', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Epitácio Pessoa', 'Torre', 7000, 58106-750, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Argemino de Sousa', 'Bessa', 44, 58777-548, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Deus Salva', 'Céu', 00, 58072-987, 'Éden', 'Babilônia', 'Paraíso', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Edson Ramalho', 'Manaíra', 66, 58451-810, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Deodoro da Fonseca', 'Miramar', 54, 58042-966, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Tamandaré', 'Cabo Branco', 71, 58421-755, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Irauna', 'Miramar', 21, 11042-220, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Píaui', 'Bairro dos Estados', 21, 10042-220, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);
INSERT INTO DBO.ENDERECO
VALUES('Lousa de Melo', 'Mandacaru', 50000, 75848-000, 'João Pessoa', 'Paraíba', 'Brasil', NULL, NULL);

--DELETE FROM DBO.ENDERECO WHERE ID = 1;
--UPDATE ENDERECO SET RUA = 'Dom Pedro' WHERE ID = 5;

INSERT INTO CLIENTE
VALUES('Marcos', 'M','marcos@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Alex', 'M','alex@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Túlio', 'M','tulio@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Maria', 'F','maria@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Fernanda', 'F','fernanda@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Flávia', 'F','flavia@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Mateus', 'M','mateus@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Ana', 'A','ana@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Cláudio', 'C','claudio@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('João', 'J','joao@gmail.com', NULL);
INSERT INTO CLIENTE
VALUES('Kleber', 'K','kleber@gmail.com', NULL);

--DELETE FROM DBO.CLIENTE WHERE ID = 1;
--UPDATE CLIENTE SET NOME = 'Mauricio' WHERE ID = 8;

INSERT INTO FUNCIONARIO
VALUES('Gabriel', '05779866698', 'M', 7500.00, NULL, 83988519315);
INSERT INTO FUNCIONARIO
VALUES('Lucas', '05779866677', 'M', 5500.00, NULL, 83988519315);
INSERT INTO FUNCIONARIO
VALUES('Alex', '05779866651', 'M', 6500.00, NULL, 83988519315);
INSERT INTO FUNCIONARIO
VALUES('Carol', '05779866635', 'F', 8700.00, NULL, 83988519315);
INSERT INTO FUNCIONARIO
VALUES('Marcia', '05779866687', 'F', 8800.00, NULL, 83988519315);
INSERT INTO FUNCIONARIO
VALUES('Daniela', '05779866693', 'F', 9250.00, NULL, 83988519315);
INSERT INTO FUNCIONARIO
VALUES('Daniela', '05779866765', 'F', 9250.00, NULL, 83988519315);
INSERT INTO FUNCIONARIO
VALUES('Olga', '05779866475', 'F', 3000.00, NULL, 83988519456);
INSERT INTO FUNCIONARIO
VALUES('Márcio', '05779866966', 'M', 9250.00, NULL, 83988519554);
INSERT INTO FUNCIONARIO
VALUES('Paulo', '05779866123', 'M', 6500.00, NULL, 83988519753);
INSERT INTO FUNCIONARIO
VALUES('Estela', '05779866100', 'F', 8000.00, NULL, 83988519031);

--DELETE FROM DBO.FUNCIONARIO WHERE ID = 1;
--UPDATE FUNCIONARIO SET NOME = 'Mauricio' WHERE ID = 5;

INSERT INTO DBO.TELEFONE
VALUES(1, 1, '83993880022');
INSERT INTO DBO.TELEFONE
VALUES(2, 2, '83987580022');
INSERT INTO DBO.TELEFONE
VALUES(3, 3, '83997580063');
INSERT INTO DBO.TELEFONE
VALUES(1, 1, '83997580022');
INSERT INTO DBO.TELEFONE
VALUES(4, 4, '83997580021');
INSERT INTO DBO.TELEFONE
VALUES(5, 5, '83997580077');
INSERT INTO DBO.TELEFONE
VALUES(6, 6, '83997580066');
INSERT INTO DBO.TELEFONE
VALUES(7, 7, '83997580010');
INSERT INTO DBO.TELEFONE
VALUES(8, 6, '83997580022');
INSERT INTO DBO.TELEFONE
VALUES(9, 5, '83997580099');
INSERT INTO DBO.TELEFONE
VALUES(10, 1, '83997580096');
INSERT INTO DBO.TELEFONE
VALUES(11, 4, '83997580054');

--DELETE FROM DBO.TELEFONE WHERE ID = 1;

INSERT INTO DBO.PAGAMENTO
VALUES('Boleto Bancário');
INSERT INTO DBO.PAGAMENTO
VALUES('Cartão de Crédito');
INSERT INTO DBO.PAGAMENTO
VALUES('Cartão de Débito');
INSERT INTO DBO.PAGAMENTO
VALUES('Pix');
INSERT INTO DBO.PAGAMENTO
VALUES('Paypal');
INSERT INTO DBO.PAGAMENTO
VALUES('Pagseguro');
INSERT INTO DBO.PAGAMENTO
VALUES('Mercado Pago');
INSERT INTO DBO.PAGAMENTO
VALUES('Depósito');

--DELETE FROM DBO.PAGAMENTO WHERE ID = 1;

INSERT INTO SERVICO
VALUES(1, 1, 5);
INSERT INTO SERVICO
VALUES(2, 2, 3);
INSERT INTO SERVICO
VALUES(2, 3, 5);
INSERT INTO SERVICO
VALUES(4, 4, 2);
INSERT INTO SERVICO
VALUES(1, 5, 2);
INSERT INTO SERVICO
VALUES(5, 6, 2);
INSERT INTO SERVICO
VALUES(2, 7, 2);
INSERT INTO SERVICO
VALUES(7, 8, 2);
INSERT INTO SERVICO
VALUES(2, 9, 2);
INSERT INTO SERVICO
VALUES(2, 10, 2);
INSERT INTO SERVICO
VALUES(3, 11, 2);

--DELETE FROM DBO.SERVICO WHERE ID = 1;

INSERT INTO DBO.ASSINATURA
VALUES(17, 5);
INSERT INTO DBO.ASSINATURA
VALUES(8, 4);
INSERT INTO DBO.ASSINATURA
VALUES(10, 7);
INSERT INTO DBO.ASSINATURA
VALUES(12, 3);
INSERT INTO DBO.ASSINATURA
VALUES(7, 6);
INSERT INTO DBO.ASSINATURA
VALUES(15, 2);
INSERT INTO DBO.ASSINATURA
VALUES(2, 5);
INSERT INTO DBO.ASSINATURA
VALUES(6, 8);
INSERT INTO DBO.ASSINATURA
VALUES(4, 6);
INSERT INTO DBO.ASSINATURA
VALUES(9, 3);
INSERT INTO DBO.ASSINATURA
VALUES(13, 6);

--DELETE FROM DBO.SERVICO WHERE ID = 1;